// The generated OpenNext entrypoint imports the middleware eagerly. Loading it
// only after the request context is installed prevents database modules from
// initializing before Cloudflare bindings (notably Hyperdrive) are visible.
// @ts-expect-error Generated by the OpenNext build before Wrangler bundles this entrypoint.
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";

type AppEnvironment = {
  CRON_SECRET?: string;
  CLOUDFLARE_INTERNAL_SECRET?: string;
  HYPERDRIVE?: { connectionString: string };
  AUTH_RATE_LIMITER?: RateLimitBinding;
  AUTH_BURST_RATE_LIMITER?: RateLimitBinding;
  FINANCIAL_RATE_LIMITER?: RateLimitBinding;
  FINANCIAL_BURST_RATE_LIMITER?: RateLimitBinding;
  API_WRITE_RATE_LIMITER?: RateLimitBinding;
  API_WRITE_BURST_RATE_LIMITER?: RateLimitBinding;
  API_READ_RATE_LIMITER?: RateLimitBinding;
  API_READ_BURST_RATE_LIMITER?: RateLimitBinding;
  PUBLIC_READ_RATE_LIMITER?: RateLimitBinding;
  PUBLIC_READ_BURST_RATE_LIMITER?: RateLimitBinding;
  WEBHOOK_RATE_LIMITER?: RateLimitBinding;
  WEBHOOK_BURST_RATE_LIMITER?: RateLimitBinding;
  TEACHER_MEDIA_KV?: KvNamespaceBinding;
  WEB_PUSH_QUEUE?: QueueProducerBinding;
};

type RateLimitBinding = {
  limit(options: { key: string }): Promise<{ success: boolean }>;
};

type ActiveRateLimitLayer = {
  binding: RateLimitBinding;
  name: "burst" | "sustained";
  limit: number;
  period: 10 | 60;
};

type RateLimitPolicy = {
  scope: "auth" | "financial" | "write" | "read" | "public-read" | "webhook";
  layers: ActiveRateLimitLayer[];
};

type KvNamespaceBinding = {
  get(key: string, options: { type: "arrayBuffer"; cacheTtl?: number }): Promise<ArrayBuffer | null>;
  put(
    key: string,
    value: ArrayBuffer | ArrayBufferView,
    options?: { metadata?: Record<string, string | number> },
  ): Promise<void>;
};

type QueueProducerBinding = {
  send(body: unknown, options?: { contentType?: "json" | "text" | "bytes" | "v8" }): Promise<void>;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type ScheduledController = {
  scheduledTime: number;
};

type QueueMessage = {
  body: unknown;
  attempts: number;
  ack(): void;
  retry(options?: { delaySeconds?: number }): void;
};

type QueueBatch = {
  queue: string;
  messages: QueueMessage[];
};

const CRON_ROUTES = {
  webPush: "/api/cron/web-push",
  communication: "/api/cron/communication-campaigns",
  passwordEmail: "/api/cron/password-email-outbox",
  jekoReconciliation: "/api/cron/jeko-reconciliation",
  notificationRetention: "/api/cron/notification-retention",
  notificationReminders: "/api/cron/notification-reminders",
  partnerReferrals: "/api/cron/partner-referrals",
} as const;

const competenceWorker = {
  async fetch(request: Request, env: AppEnvironment, ctx: WorkerExecutionContext) {
    const canonicalRedirect = redirectPublicNavigationToCanonicalHost(request);
    if (canonicalRedirect) return withSecurityHeaders(canonicalRedirect, request);

    const securityRejection = await protectPublicRequest(request, env);
    if (securityRejection) return withSecurityHeaders(securityRejection, request);

    const storedTeacherMedia = await serveTeacherMediaFromKv(request, env);
    if (storedTeacherMedia) return withSecurityHeaders(storedTeacherMedia, request);

    const response = await dispatchOpenNext(request, env, ctx);
    scheduleTeacherMediaBackfill(request, response, env, ctx);
    scheduleImmediateWebPushWake(request, response, env, ctx);
    return withSecurityHeaders(response, request);
  },

  async scheduled(
    controller: ScheduledController,
    env: AppEnvironment,
    ctx: WorkerExecutionContext,
  ) {
    const date = new Date(controller.scheduledTime);
    const routes: string[] = [CRON_ROUTES.webPush, CRON_ROUTES.communication];

    if (date.getUTCMinutes() % 5 === 0) {
      routes.push(CRON_ROUTES.passwordEmail, CRON_ROUTES.notificationReminders);
    }
    if (date.getUTCMinutes() % 10 === 0) routes.push(CRON_ROUTES.jekoReconciliation);
    if (date.getUTCHours() === 2 && date.getUTCMinutes() === 35) routes.push(CRON_ROUTES.notificationRetention);
    if (date.getUTCHours() === 1 && date.getUTCMinutes() === 30) routes.push(CRON_ROUTES.partnerReferrals);

    ctx.waitUntil(Promise.all(routes.map((route) => invokeCronRoute(route, env, ctx))).then(() => undefined));
  },

  async queue(batch: QueueBatch, env: AppEnvironment, ctx: WorkerExecutionContext) {
    await Promise.all(batch.messages.map(async (message) => {
      try {
        const queue = classifyQueue(batch.queue);
        const response = await dispatchOpenNext(new Request(
          "https://competence.internal/api/internal/cloudflare-queue",
          {
            method: "POST",
            headers: {
              "authorization": `Bearer ${requireSecret(env.CLOUDFLARE_INTERNAL_SECRET, "CLOUDFLARE_INTERNAL_SECRET")}`,
              "content-type": "application/json",
            },
            body: JSON.stringify({ queue, message: message.body, attempts: message.attempts }),
          },
        ), env, ctx);

        if (!response.ok) throw new Error(`Traitement ${queue} refusé (${response.status}).`);
        message.ack();
      } catch (error) {
        console.error(JSON.stringify({
          level: "error",
          scope: "cloudflare-queue-consumer",
          queue: batch.queue,
          attempts: message.attempts,
          error: error instanceof Error ? error.message : "Traitement impossible.",
        }));
        if (message.attempts >= 6) message.ack();
        else message.retry({ delaySeconds: Math.min(300, 2 ** message.attempts * 5) });
      }
    }));
  },
};

export default competenceWorker;

async function invokeCronRoute(route: string, env: AppEnvironment, ctx: WorkerExecutionContext) {
  const response = await dispatchOpenNext(new Request(`https://competence.internal${route}`, {
    method: "GET",
    headers: {
      "authorization": `Bearer ${requireSecret(env.CRON_SECRET, "CRON_SECRET")}`,
      "x-cloudflare-cron": "true",
    },
  }), env, ctx);
  if (!response.ok) throw new Error(`Cron ${route} refusé (${response.status}).`);
}

async function dispatchOpenNext(
  request: Request,
  env: AppEnvironment,
  ctx: WorkerExecutionContext,
) {
  return runWithCloudflareRequestContext(request, env, ctx, async () => {
    if (env.HYPERDRIVE?.connectionString) {
      // OpenNext copie les secrets texte dans process.env. Remplacer ici
      // l'URL d'origine garantit que tout import Prisma chargé ensuite passe
      // par Hyperdrive, même lorsqu'un middleware importe la base très tôt.
      process.env.DATABASE_URL = env.HYPERDRIVE.connectionString;
    }
    const { runWithDatabaseRequestContext } = await import("./src/lib/db");
    return runWithDatabaseRequestContext(async () => {
      // @ts-expect-error Generated by the OpenNext build before Wrangler bundles this entrypoint.
      const { default: openNextWorker } = await import("./.open-next/worker.js");
      return openNextWorker.fetch(request, env, ctx);
    });
  });
}

function redirectPublicNavigationToCanonicalHost(request: Request) {
  const url = new URL(request.url);
  if (url.hostname.toLowerCase() !== "competence.ci") return null;
  if (request.method !== "GET" && request.method !== "HEAD") return null;

  // API requests remain on their current host so a stale, already-open page
  // can finish authentication without losing its host-only CSRF cookie.
  if (url.pathname.startsWith("/api/")) return null;
  const acceptsHtml = request.headers.get("accept")?.includes("text/html") ?? false;
  const navigation = request.headers.get("sec-fetch-mode") === "navigate";
  if (!acceptsHtml && !navigation) return null;

  url.hostname = "www.competence.ci";
  return Response.redirect(url.toString(), 308);
}

function classifyQueue(queueName: string): "web-push" | "communication" {
  if (queueName.includes("web-push")) return "web-push";
  if (queueName.includes("communication")) return "communication";
  throw new Error(`File Cloudflare inconnue : ${queueName}`);
}

function requireSecret(value: string | undefined, name: string) {
  if (value?.trim()) return value.trim();
  throw new Error(`${name} est obligatoire.`);
}

async function protectPublicRequest(request: Request, env: AppEnvironment) {
  const url = new URL(request.url);
  const method = request.method.toUpperCase();

  if (!isAllowedMutationOrigin(request, url, method)) {
    return jsonSecurityError(403, "Requête refusée.");
  }

  const contentLength = Number(request.headers.get("content-length") || "0");
  if (Number.isFinite(contentLength) && contentLength > maximumRequestBytes(url.pathname)) {
    return jsonSecurityError(413, "Requête trop volumineuse.");
  }

  const policy = selectRateLimitPolicy(url.pathname, method, env);
  if (!policy) return null;

  const key = await buildRateLimitKey(request, url.pathname, policy.scope);
  const outcomes = await Promise.all(policy.layers.map(async (layer) => {
    try {
      return { layer, result: await layer.binding.limit({ key }), error: null };
    } catch (error) {
      return { layer, result: null, error };
    }
  }));

  for (const outcome of outcomes) {
    if (!outcome.error) continue;
    // Une panne d'un compteur ne doit pas rendre la plateforme indisponible.
    // Les autres couches et les contrôles métier restent actifs.
    console.error(JSON.stringify({
      level: "error",
      scope: "cloudflare-rate-limit-unavailable",
      policy: policy.scope,
      layer: outcome.layer.name,
      cfRay: request.headers.get("cf-ray"),
      error: outcome.error instanceof Error ? outcome.error.message : "Compteur indisponible.",
    }));
  }

  const rejected = outcomes.filter((outcome) => outcome.result?.success === false);
  if (rejected.length === 0) return null;

  const retryAfter = Math.max(...rejected.map((outcome) => outcome.layer.period));
  console.warn(JSON.stringify({
    level: "warn",
    scope: "cloudflare-rate-limit",
    policy: policy.scope,
    layers: rejected.map((outcome) => outcome.layer.name),
    pathname: normalizeRateLimitRoute(url.pathname),
    cfRay: request.headers.get("cf-ray"),
  }));
  return new Response(JSON.stringify({
    error: retryAfter >= 60
      ? "Trop de tentatives. Patientez une minute puis réessayez."
      : "Trop d'actions rapprochées. Patientez quelques secondes puis réessayez.",
    code: "RATE_LIMITED",
    retryAfterSeconds: retryAfter,
  }), {
    status: 429,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
      "retry-after": String(retryAfter),
      "ratelimit-policy": policy.layers.map((layer) => `${layer.limit};w=${layer.period}`).join(", "),
      "x-competence-rate-limit": policy.scope,
    },
  });
}

function selectRateLimitPolicy(pathname: string, method: string, env: AppEnvironment): RateLimitPolicy | null {
  const isMutation = !["GET", "HEAD", "OPTIONS"].includes(method);
  if (!pathname.startsWith("/api/")) return null;
  if (pathname.startsWith("/api/webhooks/")) {
    return createRateLimitPolicy("webhook", [
      { binding: env.WEBHOOK_BURST_RATE_LIMITER, name: "burst", limit: 2_000, period: 10 },
      { binding: env.WEBHOOK_RATE_LIMITER, name: "sustained", limit: 10_000, period: 60 },
    ]);
  }
  if (pathname.startsWith("/api/internal/") || pathname.startsWith("/api/cron/")) {
    return null;
  }

  const authSensitive = isMutation && (
    pathname.startsWith("/api/auth/")
    || pathname === "/api/professor/password-assistance"
  );
  if (authSensitive) {
    return createRateLimitPolicy("auth", [
      { binding: env.AUTH_BURST_RATE_LIMITER, name: "burst", limit: 6, period: 10 },
      { binding: env.AUTH_RATE_LIMITER, name: "sustained", limit: 20, period: 60 },
    ]);
  }

  const financialSensitive = isMutation && (
    pathname.startsWith("/api/bookings")
    || pathname.startsWith("/api/professor/payout-requests")
    || pathname.startsWith("/api/admin/teacher-payout")
    || pathname.startsWith("/api/admin/transactions")
    || pathname.startsWith("/api/admin/refund")
  );
  if (financialSensitive) {
    return createRateLimitPolicy("financial", [
      { binding: env.FINANCIAL_BURST_RATE_LIMITER, name: "burst", limit: 12, period: 10 },
      { binding: env.FINANCIAL_RATE_LIMITER, name: "sustained", limit: 40, period: 60 },
    ]);
  }

  if (isMutation) {
    return createRateLimitPolicy("write", [
      { binding: env.API_WRITE_BURST_RATE_LIMITER, name: "burst", limit: 45, period: 10 },
      { binding: env.API_WRITE_RATE_LIMITER, name: "sustained", limit: 180, period: 60 },
    ]);
  }

  const publicRead = method === "GET" && (
    pathname.startsWith("/api/teacher-photos/")
    || pathname === "/api/teachers"
    || pathname.startsWith("/api/teachers/")
    || pathname === "/api/course-catalog"
    || pathname === "/api/subjects"
    || pathname === "/api/levels"
    || pathname === "/api/communes"
  );
  if (publicRead) {
    return createRateLimitPolicy("public-read", [
      { binding: env.PUBLIC_READ_BURST_RATE_LIMITER, name: "burst", limit: 120, period: 10 },
      { binding: env.PUBLIC_READ_RATE_LIMITER, name: "sustained", limit: 600, period: 60 },
    ]);
  }

  if (method === "GET" || method === "HEAD") {
    return createRateLimitPolicy("read", [
      { binding: env.API_READ_BURST_RATE_LIMITER, name: "burst", limit: 75, period: 10 },
      { binding: env.API_READ_RATE_LIMITER, name: "sustained", limit: 300, period: 60 },
    ]);
  }

  return null;
}

function createRateLimitPolicy(
  scope: RateLimitPolicy["scope"],
  layers: Array<Omit<ActiveRateLimitLayer, "binding"> & { binding?: RateLimitBinding }>,
): RateLimitPolicy | null {
  const activeLayers = layers.flatMap((layer) => layer.binding ? [{ ...layer, binding: layer.binding }] : []);
  return activeLayers.length > 0 ? { scope, layers: activeLayers } : null;
}

async function buildRateLimitKey(request: Request, pathname: string, scope: string) {
  const route = normalizeRateLimitRoute(pathname);
  const identity = await resolveRateLimitIdentity(request, scope);
  const value = `${scope}|${route}|${identity}`;
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

function normalizeRateLimitRoute(pathname: string) {
  return pathname
    .replace(/\/c[a-z0-9]{20,}(?=\/|$)/gi, "/:id")
    .replace(/\/[0-9a-f]{8}-[0-9a-f-]{27,}(?=\/|$)/gi, "/:id")
    .replace(/\/\d{4,}(?=\/|$)/g, "/:id");
}

async function resolveRateLimitIdentity(request: Request, scope: string) {
  if (scope === "auth") {
    const accountIdentifier = await extractAuthAccountIdentifier(request);
    if (accountIdentifier) return `account:${accountIdentifier}`;
  }

  const session = readSessionCookie(request.headers.get("cookie"));
  if (session) return `session:${session}`;

  const ip = request.headers.get("cf-connecting-ip")
    || request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()
    || "unknown";
  return `network:${ip}`;
}

async function extractAuthAccountIdentifier(request: Request) {
  if (!['POST', 'PUT', 'PATCH'].includes(request.method.toUpperCase())) return null;
  const contentType = request.headers.get("content-type")?.toLowerCase() || "";
  const acceptedFields = ["email", "phone", "identifier", "username"];
  try {
    if (contentType.includes("application/json")) {
      const body = await request.clone().json() as Record<string, unknown>;
      for (const field of acceptedFields) {
        const normalized = normalizeAccountIdentifier(body?.[field]);
        if (normalized) return normalized;
      }
    } else if (contentType.includes("application/x-www-form-urlencoded") || contentType.includes("multipart/form-data")) {
      const form = await request.clone().formData();
      for (const field of acceptedFields) {
        const normalized = normalizeAccountIdentifier(form.get(field));
        if (normalized) return normalized;
      }
    }
  } catch {
    return null;
  }
  return null;
}

function normalizeAccountIdentifier(value: unknown) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().toLowerCase().slice(0, 160);
  if (!normalized) return null;
  if (normalized.includes("@")) return normalized;
  const phone = normalized.replace(/[^\d+]/g, "");
  return phone.length >= 6 ? phone : normalized;
}

function readSessionCookie(cookieHeader: string | null) {
  if (!cookieHeader) return null;
  const sessionNames = new Set([
    "authjs.session-token",
    "__Secure-authjs.session-token",
    "next-auth.session-token",
    "__Secure-next-auth.session-token",
  ]);
  for (const part of cookieHeader.split(";")) {
    const separator = part.indexOf("=");
    if (separator < 1) continue;
    const name = part.slice(0, separator).trim();
    if (!sessionNames.has(name)) continue;
    const value = part.slice(separator + 1).trim();
    if (value) return value.slice(0, 1_024);
  }
  return null;
}

function maximumRequestBytes(pathname: string) {
  if (pathname === "/api/admin/uploads/teacher-photo" || pathname === "/api/professor/profile-media") {
    return 10 * 1024 * 1024;
  }
  if (pathname === "/api/admin/teachers/analyze-cv") return 15 * 1024 * 1024;
  return 2 * 1024 * 1024;
}

function isAllowedMutationOrigin(request: Request, url: URL, method: string) {
  if (["GET", "HEAD", "OPTIONS"].includes(method)) return true;
  if (url.pathname.startsWith("/api/webhooks/")) return true;

  const origin = request.headers.get("origin");
  if (!origin) return true;
  try {
    const originUrl = new URL(origin);
    return originUrl.protocol === "https:"
      && (
        originUrl.hostname.toLowerCase() === url.hostname.toLowerCase()
        || ["competence.ci", "www.competence.ci"].includes(originUrl.hostname.toLowerCase())
      );
  } catch {
    return false;
  }
}

function jsonSecurityError(status: number, error: string) {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

function withSecurityHeaders(response: Response, request: Request) {
  const headers = new Headers(response.headers);
  const pathname = new URL(request.url).pathname;
  headers.set("x-competence-runtime", "cloudflare-wrapper-v4");
  headers.delete("x-powered-by");
  headers.set("x-content-type-options", "nosniff");
  headers.set("x-frame-options", "SAMEORIGIN");
  headers.set("referrer-policy", "strict-origin-when-cross-origin");
  headers.set("cross-origin-opener-policy", "same-origin-allow-popups");
  headers.set("x-permitted-cross-domain-policies", "none");
  headers.set("origin-agent-cluster", "?1");
  headers.set(
    "content-security-policy",
    "base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self' https://*.jeko.africa; upgrade-insecure-requests",
  );
  if (
    pathname.startsWith("/api/auth/")
    || pathname.startsWith("/api/admin/")
    || pathname.startsWith("/api/client/")
    || pathname.startsWith("/api/professor/")
  ) {
    headers.set("cache-control", "private, no-store, max-age=0");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function serveTeacherMediaFromKv(request: Request, env: AppEnvironment) {
  if (request.method !== "GET" && request.method !== "HEAD") return null;
  const mediaId = teacherMediaIdFromPath(new URL(request.url).pathname);
  if (!mediaId || !env.TEACHER_MEDIA_KV) return null;

  try {
    const data = await env.TEACHER_MEDIA_KV.get(teacherMediaKey(mediaId), {
      type: "arrayBuffer",
      cacheTtl: 86_400,
    });
    if (!data) return null;
    return new Response(request.method === "HEAD" ? null : data, {
      status: 200,
      headers: {
        "content-type": "image/webp",
        "content-length": String(data.byteLength),
        "cache-control": "public, max-age=31536000, immutable",
        "etag": `"teacher-media-${mediaId}"`,
        "x-competence-media": "cloudflare-kv",
      },
    });
  } catch (error) {
    console.error(JSON.stringify({
      level: "error",
      scope: "teacher-media-kv-read",
      mediaId,
      error: error instanceof Error ? error.message : "Lecture KV impossible.",
    }));
    return null;
  }
}

function scheduleTeacherMediaBackfill(
  request: Request,
  response: Response,
  env: AppEnvironment,
  ctx: WorkerExecutionContext,
) {
  if (request.method !== "GET" || !response.ok || !env.TEACHER_MEDIA_KV) return;
  const mediaId = teacherMediaIdFromPath(new URL(request.url).pathname);
  if (!mediaId) return;

  const copy = response.clone();
  ctx.waitUntil(copy.arrayBuffer()
    .then((data) => env.TEACHER_MEDIA_KV!.put(teacherMediaKey(mediaId), data, {
      metadata: { contentType: copy.headers.get("content-type") || "image/webp" },
    }))
    .catch((error) => {
      console.error(JSON.stringify({
        level: "error",
        scope: "teacher-media-kv-backfill",
        mediaId,
        error: error instanceof Error ? error.message : "Copie KV impossible.",
      }));
    }));
}

function scheduleImmediateWebPushWake(
  request: Request,
  response: Response,
  env: AppEnvironment,
  ctx: WorkerExecutionContext,
) {
  if (!env.WEB_PUSH_QUEUE || !response.ok) return;
  if (["GET", "HEAD", "OPTIONS"].includes(request.method.toUpperCase())) return;
  const pathname = new URL(request.url).pathname;
  if (!pathname.startsWith("/api/")) return;
  if (pathname.startsWith("/api/internal/") || pathname.startsWith("/api/cron/")) return;

  const createdAt = new Date().toISOString();
  const message = {
    kind: "FLUSH_OUTBOX",
    reason: "outbox_created",
    limit: 500,
    createdAt,
    idempotencyKey: `web-push-mutation-${createdAt}-${crypto.randomUUID()}`,
  };
  ctx.waitUntil(env.WEB_PUSH_QUEUE.send(message, { contentType: "json" }).catch((error) => {
    console.error(JSON.stringify({
      level: "error",
      scope: "web-push-immediate-wake",
      pathname,
      error: error instanceof Error ? error.message : "Publication immédiate impossible.",
    }));
  }));
}

function teacherMediaIdFromPath(pathname: string) {
  const match = pathname.match(/^\/api\/teacher-photos\/(c[a-z0-9]{20,})$/i);
  return match?.[1] || null;
}

function teacherMediaKey(mediaId: string) {
  return `teacher-photos/${mediaId}`;
}
