// @ts-expect-error Generated by the OpenNext build before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

// OpenNext exports these handlers even when the default cache configuration does not use them.
// @ts-expect-error Generated by the OpenNext build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

type AppEnvironment = {
  CRON_SECRET?: string;
  CLOUDFLARE_INTERNAL_SECRET?: string;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type ScheduledController = {
  scheduledTime: number;
};

type QueueMessage = {
  body: unknown;
  attempts: number;
  ack(): void;
  retry(options?: { delaySeconds?: number }): void;
};

type QueueBatch = {
  queue: string;
  messages: QueueMessage[];
};

const CRON_ROUTES = {
  webPush: "/api/cron/web-push",
  communication: "/api/cron/communication-campaigns",
  passwordEmail: "/api/cron/password-email-outbox",
  jekoReconciliation: "/api/cron/jeko-reconciliation",
  notificationRetention: "/api/cron/notification-retention",
  notificationReminders: "/api/cron/notification-reminders",
  partnerReferrals: "/api/cron/partner-referrals",
} as const;

const competenceWorker = {
  fetch(request: Request, env: AppEnvironment, ctx: WorkerExecutionContext) {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(
    controller: ScheduledController,
    env: AppEnvironment,
    ctx: WorkerExecutionContext,
  ) {
    const date = new Date(controller.scheduledTime);
    const routes: string[] = [CRON_ROUTES.webPush, CRON_ROUTES.communication];

    if (date.getUTCMinutes() % 5 === 0) routes.push(CRON_ROUTES.passwordEmail);
    if (date.getUTCMinutes() % 10 === 0) routes.push(CRON_ROUTES.jekoReconciliation);
    if (date.getUTCHours() === 2 && date.getUTCMinutes() === 35) routes.push(CRON_ROUTES.notificationRetention);
    if (date.getUTCHours() === 8 && date.getUTCMinutes() === 0) routes.push(CRON_ROUTES.notificationReminders);
    if (date.getUTCHours() === 1 && date.getUTCMinutes() === 30) routes.push(CRON_ROUTES.partnerReferrals);

    ctx.waitUntil(Promise.all(routes.map((route) => invokeCronRoute(route, env, ctx))).then(() => undefined));
  },

  async queue(batch: QueueBatch, env: AppEnvironment, ctx: WorkerExecutionContext) {
    await Promise.all(batch.messages.map(async (message) => {
      try {
        const queue = classifyQueue(batch.queue);
        const response = await openNextWorker.fetch(new Request(
          "https://competence.internal/api/internal/cloudflare-queue",
          {
            method: "POST",
            headers: {
              "authorization": `Bearer ${requireSecret(env.CLOUDFLARE_INTERNAL_SECRET, "CLOUDFLARE_INTERNAL_SECRET")}`,
              "content-type": "application/json",
            },
            body: JSON.stringify({ queue, message: message.body, attempts: message.attempts }),
          },
        ), env, ctx);

        if (!response.ok) throw new Error(`Traitement ${queue} refusé (${response.status}).`);
        message.ack();
      } catch (error) {
        console.error(JSON.stringify({
          level: "error",
          scope: "cloudflare-queue-consumer",
          queue: batch.queue,
          attempts: message.attempts,
          error: error instanceof Error ? error.message : "Traitement impossible.",
        }));
        if (message.attempts >= 6) message.ack();
        else message.retry({ delaySeconds: Math.min(300, 2 ** message.attempts * 5) });
      }
    }));
  },
};

export default competenceWorker;

async function invokeCronRoute(route: string, env: AppEnvironment, ctx: WorkerExecutionContext) {
  const response = await openNextWorker.fetch(new Request(`https://competence.internal${route}`, {
    method: "GET",
    headers: {
      "authorization": `Bearer ${requireSecret(env.CRON_SECRET, "CRON_SECRET")}`,
      "x-cloudflare-cron": "true",
    },
  }), env, ctx);
  if (!response.ok) throw new Error(`Cron ${route} refusé (${response.status}).`);
}

function classifyQueue(queueName: string): "web-push" | "communication" {
  if (queueName.includes("web-push")) return "web-push";
  if (queueName.includes("communication")) return "communication";
  throw new Error(`File Cloudflare inconnue : ${queueName}`);
}

function requireSecret(value: string | undefined, name: string) {
  if (value?.trim()) return value.trim();
  throw new Error(`${name} est obligatoire.`);
}
