insert into competence."Commune" ("id", "name", "zone", "createdAt")
values
  ('ci-abidjan', 'Abidjan', 'District Autonome d''Abidjan', now()),
  ('ci-cocody', 'Cocody', 'Abidjan', now()),
  ('ci-angre', 'Angré', 'Abidjan', now()),
  ('ci-riviera', 'Riviera', 'Abidjan', now()),
  ('ci-deux-plateaux', 'Deux Plateaux', 'Abidjan', now()),
  ('ci-bingerville', 'Bingerville', 'Abidjan', now()),
  ('ci-yopougon', 'Yopougon', 'Abidjan', now()),
  ('ci-abobo', 'Abobo', 'Abidjan', now()),
  ('ci-anyama', 'Anyama', 'Abidjan', now()),
  ('ci-marcory', 'Marcory', 'Abidjan', now()),
  ('ci-koumassi', 'Koumassi', 'Abidjan', now()),
  ('ci-treichville', 'Treichville', 'Abidjan', now()),
  ('ci-plateau', 'Plateau', 'Abidjan', now()),
  ('ci-port-bouet', 'Port-Bouët', 'Abidjan', now()),
  ('ci-adjame', 'Adjamé', 'Abidjan', now()),
  ('ci-attecoube', 'Attécoubé', 'Abidjan', now()),
  ('ci-songon', 'Songon', 'Abidjan', now()),
  ('ci-grand-bassam', 'Grand-Bassam', 'Sud-Comoé', now()),
  ('ci-bonoua', 'Bonoua', 'Sud-Comoé', now()),
  ('ci-aboisso', 'Aboisso', 'Sud-Comoé', now()),
  ('ci-adiake', 'Adiaké', 'Sud-Comoé', now()),
  ('ci-tiapoum', 'Tiapoum', 'Sud-Comoé', now()),
  ('ci-noe', 'Noé', 'Sud-Comoé', now()),
  ('ci-dabou', 'Dabou', 'Grands-Ponts', now()),
  ('ci-jacqueville', 'Jacqueville', 'Grands-Ponts', now()),
  ('ci-grand-lahou', 'Grand-Lahou', 'Grands-Ponts', now()),
  ('ci-alepe', 'Alépé', 'La Mé', now()),
  ('ci-adzope', 'Adzopé', 'La Mé', now()),
  ('ci-akoupe', 'Akoupé', 'La Mé', now()),
  ('ci-affery', 'Afféry', 'La Mé', now()),
  ('ci-yakasse-attobrou', 'Yakassé-Attobrou', 'La Mé', now()),
  ('ci-agboville', 'Agboville', 'Agnéby-Tiassa', now()),
  ('ci-azaguie', 'Azaguié', 'Agnéby-Tiassa', now()),
  ('ci-tiassale', 'Tiassalé', 'Agnéby-Tiassa', now()),
  ('ci-sikensi', 'Sikensi', 'Agnéby-Tiassa', now()),
  ('ci-abengourou', 'Abengourou', 'Indénié-Djuablin', now()),
  ('ci-agnibilekrou', 'Agnibilékrou', 'Indénié-Djuablin', now()),
  ('ci-niable', 'Niablé', 'Indénié-Djuablin', now()),
  ('ci-bettie', 'Bettié', 'Indénié-Djuablin', now()),
  ('ci-bondoukou', 'Bondoukou', 'Gontougo', now()),
  ('ci-tanda', 'Tanda', 'Gontougo', now()),
  ('ci-koun-fao', 'Koun-Fao', 'Gontougo', now()),
  ('ci-bouna', 'Bouna', 'Bounkani', now()),
  ('ci-doropo', 'Doropo', 'Bounkani', now()),
  ('ci-nassian', 'Nassian', 'Bounkani', now()),
  ('ci-bouake', 'Bouaké', 'Gbêkê', now()),
  ('ci-beoumi', 'Béoumi', 'Gbêkê', now()),
  ('ci-sakassou', 'Sakassou', 'Gbêkê', now()),
  ('ci-botro', 'Botro', 'Gbêkê', now()),
  ('ci-katiola', 'Katiola', 'Hambol', now()),
  ('ci-dabakala', 'Dabakala', 'Hambol', now()),
  ('ci-niakaramadougou', 'Niakaramadougou', 'Hambol', now()),
  ('ci-yamoussoukro', 'Yamoussoukro', 'District Autonome de Yamoussoukro', now()),
  ('ci-attiegouakro', 'Attiégouakro', 'District Autonome de Yamoussoukro', now()),
  ('ci-toumodi', 'Toumodi', 'Bélier', now()),
  ('ci-tiebissou', 'Tiébissou', 'Bélier', now()),
  ('ci-dimbokro', 'Dimbokro', 'N''Zi', now()),
  ('ci-bocanda', 'Bocanda', 'N''Zi', now()),
  ('ci-daoukro', 'Daoukro', 'Iffou', now()),
  ('ci-mbahiakro', 'M''Bahiakro', 'Iffou', now()),
  ('ci-prikro', 'Prikro', 'Iffou', now()),
  ('ci-daloa', 'Daloa', 'Haut-Sassandra', now()),
  ('ci-vavoua', 'Vavoua', 'Haut-Sassandra', now()),
  ('ci-issia', 'Issia', 'Haut-Sassandra', now()),
  ('ci-zoukougbeu', 'Zoukougbeu', 'Haut-Sassandra', now()),
  ('ci-gagnoa', 'Gagnoa', 'Gôh', now()),
  ('ci-oume', 'Oumé', 'Gôh', now()),
  ('ci-sinfra', 'Sinfra', 'Marahoué', now()),
  ('ci-bouafle', 'Bouaflé', 'Marahoué', now()),
  ('ci-zuenoula', 'Zuénoula', 'Marahoué', now()),
  ('ci-san-pedro', 'San-Pédro', 'San-Pédro', now()),
  ('ci-sassandra', 'Sassandra', 'Gbôklè', now()),
  ('ci-tabou', 'Tabou', 'San-Pédro', now()),
  ('ci-grand-bereby', 'Grand-Béréby', 'San-Pédro', now()),
  ('ci-soubre', 'Soubré', 'Nawa', now()),
  ('ci-meagui', 'Méagui', 'Nawa', now()),
  ('ci-buyo', 'Buyo', 'Nawa', now()),
  ('ci-divo', 'Divo', 'Lôh-Djiboua', now()),
  ('ci-lakota', 'Lakota', 'Lôh-Djiboua', now()),
  ('ci-guitry', 'Guitry', 'Lôh-Djiboua', now()),
  ('ci-fresco', 'Fresco', 'Gbôklè', now()),
  ('ci-korhogo', 'Korhogo', 'Poro', now()),
  ('ci-sinematiali', 'Sinématiali', 'Poro', now()),
  ('ci-ferkessedougou', 'Ferkessédougou', 'Tchologo', now()),
  ('ci-ouangolodougou', 'Ouangolodougou', 'Tchologo', now()),
  ('ci-boundiali', 'Boundiali', 'Bagoué', now()),
  ('ci-tengrela', 'Tengréla', 'Bagoué', now()),
  ('ci-odienne', 'Odienné', 'Kabadougou', now()),
  ('ci-madinani', 'Madinani', 'Kabadougou', now()),
  ('ci-minignan', 'Minignan', 'Folon', now()),
  ('ci-touba', 'Touba', 'Bafing', now()),
  ('ci-mankono', 'Mankono', 'Béré', now()),
  ('ci-seguela', 'Séguéla', 'Worodougou', now()),
  ('ci-kani', 'Kani', 'Worodougou', now()),
  ('ci-man', 'Man', 'Tonkpi', now()),
  ('ci-danane', 'Danané', 'Tonkpi', now()),
  ('ci-biankouma', 'Biankouma', 'Tonkpi', now()),
  ('ci-zouan-hounien', 'Zouan-Hounien', 'Tonkpi', now()),
  ('ci-guiglo', 'Guiglo', 'Cavally', now()),
  ('ci-duekoue', 'Duékoué', 'Guémon', now()),
  ('ci-bangolo', 'Bangolo', 'Guémon', now()),
  ('ci-toulepleu', 'Toulépleu', 'Cavally', now()),
  ('ci-blolequin', 'Bloléquin', 'Cavally', now())
on conflict ("name") do update
set "zone" = excluded."zone";
